### PR TITLE
Sagemaker Data Science Environment

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
Adds the following:

1. The necessary role for creating Notebook instances in Sagemaker
2. A Lambda function for automatically shutting down Notebook instances
3. A cron-rule to run said Lambda nightly at 2am PT
4. Examples for creating a standard notebook instance or a "keepalive" instance (one that doesn't get shutdown nightly)
5. A Makefile to package and deploy the stack nightly

### CODE REVIEW

**Comment by karenng-civicsoftware** [comment]
@DingoEatingFuzz one problem that I have recommending Google Colaboratory to analyze data is that it can't list the directory structure of the public hacko-data-archive S3 bucket. I suspect it is a permission issue. Is it possible for you to fix the issue? 

[StackOverflow post listing a possible solution](https://stackoverflow.com/questions/37360343/how-to-list-content-from-a-public-amazon-s3-bucket) It states permission issue can inhibit listing the directory content

**Comment by DingoEatingFuzz** [comment]
It is an intentional permission setting, yet. I'd rather not let the world traverse through that s3 bucket. 

What is the desired workflow? Why is using the aws console to find files prohibitive?

**Comment by DingoEatingFuzz** [comment]
Enough time has passed on this that I am going to merge it as is. If anyone last second objects, we can always make changes later.

**Comment by MikeTheCanuck** [comment]
Sorry, didn’t realise this was still an active request.

Has anyone tested this change in a CF deploy *not* against our `HackO-integration` stack?  Deploying straight into production is never the right approach (even acknowledging we’ve taken the not-right approach multiple times in the past).

**Comment by DingoEatingFuzz** [comment]
Yes, I built this against a personal aws account, which is why the s3 bucket is configurable. I also made sure to namespace the cfn requirements to the sagemaker path to avoid clobbering existing state.

This deployed to the hacko account cleanly last night. 

It's also a new stack, which decreased the potential blast radius of a bad deployment.

**Comment by MikeTheCanuck** [comment]
Could you do us a favour and document in the README a distinction between this standalone infrastructure and the remaining fully-integrated infrastructure?  I have a feeling that by this time next year, it'll be a big mystery to understand how this isn't integrated with the main master.yaml(s).

**Pull request merged**
